languaage: node_js
node_js:
  -"8"
script:
  - "echo started build"
install:
  - npm install -g firebase-tools
after_success:
 script:
  - "ls" 
 - firebase deploy --public ./build --token $FIREBASE_TOKEN
  
    
