languaage: node_js
node_js:
  -"8"
script:
  - "echo deploying"
install:
  - npm install -g firebase-tools
after_success:
  script:
    - "ll"
  - firebase deploy --public ./build --token $FIREBASE_TOKEN
  
    
