languaage: node_js
node_js:
  -"8"
script:
  - "echo started to build ... "

install:
  - npm install -g firebase-tools
after_success:
 - firebase deploy --public ./build --token $FIREBASE_TOKEN
  
    
